[features]
seeds = false
skip-lint = false

[programs.localnet]
xcm_htlc = "64GMKYfXd99kVEcNm3DyJPSJB6HhKTBMR5hcncpf5zEx"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
