//! # xcm_htlc — Nightspire cross-chain marketplace HTLC escrow (Solana leg)
//!
//! Non-custodial hashed-timelock escrow for atomic swaps where Solana is one leg
//! (the counter-leg lives on EVM or Chia). Follows SPEC.md §5b.
//!
//! ## PDA seeds (deterministic escrow address)
//!
//! ```text
//! escrow_pda = find_program_address(["htlc", fill_id, hashlock], program_id)
//! ```
//! where `fill_id = sha256(offerId || fillNonce)` (unique per fill, §5) and
//! `hashlock = sha256(secret)` (SHA-256 via `solana_program::hash::hash`, which is
//! byte-compatible with the EVM `sha256` precompile and Chia's `sha256` operator).
//!
//! ## Branches
//!
//! * `initialize` — lock funds into the escrow (native SOL or SPL).
//! * `withdraw(preimage)` — claim branch: `sha256(preimage) == hashlock` and
//!   `now < timelock` → pays `receiver`. Honors the exclusive claim window (§8):
//!   while `exclusive_until > now`, only `exclusive_claimer` may call.
//! * `refund` — timelock branch: `now >= timelock` → pays `refund_addr`. Anyone may call.
//! * `arbitrate` — **MEDIATED** (opt-in at lock time only). If `arbiter` was set, the
//!   arbiter can unilaterally redirect the escrowed funds on its ed25519 signature
//!   alone — no counterparty signature required. Authorization is proven by a
//!   native Ed25519Program signature-verification instruction placed immediately
//!   before this instruction in the same transaction; the handler inspects it via
//!   the instructions sysvar and checks program id, signer pubkey, and message
//!   (the runtime itself verifies the cryptographic signature). See the trust
//!   note on [`xcm_htlc::arbitrate`]. When `arbiter` is `None` (default) the swap
//!   is pure HTLC: math-only trust, no third party can move the funds.
//!
//! ## Rent回收 (account closure)
//!
//! The escrow PDA is closed on every terminal branch. Reclaimed rent follows the
//! branch's primary funds destination: `withdraw` → `receiver`, `refund` →
//! `refund_addr`, `arbitrate` → `refund_addr` (documented neutral default; the
//! arbiter's signed split must account for exactly `amount`, rent is dust).
//! The SPL vault token account is closed via the SPL `CloseAccount` instruction
//! (authority = escrow PDA) to the same destination.

use anchor_lang::prelude::*;
use anchor_spl::token::{self, TokenAccount};
use solana_program::{
    ed25519_program,
    hash::hash,
    program::invoke,
    sysvar::instructions::{
        load_current_index_checked, load_instruction_at_checked, ID as IX_SYSVAR_ID,
    },
    system_instruction,
};

declare_id!("64GMKYfXd99kVEcNm3DyJPSJB6HhKTBMR5hcncpf5zEx");

/// PDA seed prefix for escrow accounts.
pub const HTLC_SEED: &[u8] = b"htlc";
/// Domain separator for arbiter authorization messages (MEDIATED branch).
pub const ARBITRATE_DOMAIN: &[u8] = b"XCM-ARBITRATE-v1";

#[program]
pub mod xcm_htlc {
    use super::*;

    /// Lock funds into a new HTLC escrow.
    ///
    /// * `receiver` — address the claim branch pays to (explicit per-leg binding, §5).
    /// * `refund_addr` — address the timelock branch pays to. EXPLICIT: refund never
    ///   assumes/implies a sender.
    /// * `hashlock` — `sha256(secret)`; the secret is generated by the MAKER per fill.
    /// * `timelock` — unix timestamp; first-locked leg gets the LONGER timelock (§9).
    /// * `mint` — `None` = native SOL, `Some(mint)` = SPL token escrow.
    /// * `amount` — escrowed amount in lamports / base units.
    /// * `fill_id` — `sha256(offerId || fillNonce)`; bound into the PDA seeds.
    /// * `arbiter` — opt-in **MEDIATED** arbitration key. `None` = pure HTLC.
    /// * `exclusive_claimer` / `exclusive_until` — auction-winner exclusive claim
    ///   window (§8). While `exclusive_until > now`, only `exclusive_claimer` may
    ///   call `withdraw`.
    ///
    /// For SPL fills the caller must pre-create the escrow vault token account
    /// (authority = escrow PDA, e.g. its associated token address with
    /// `allowOwnerOffCurve`) in the same transaction before this instruction; the
    /// handler validates mint/authority/zero-balance rather than trusting it.
    #[allow(clippy::too_many_arguments)]
    pub fn initialize(
        ctx: Context<Initialize>,
        receiver: Pubkey,
        refund_addr: Pubkey,
        hashlock: [u8; 32],
        timelock: i64,
        mint: Option<Pubkey>,
        amount: u64,
        fill_id: [u8; 32],
        arbiter: Option<Pubkey>,
        exclusive_claimer: Option<Pubkey>,
        exclusive_until: i64,
    ) -> Result<()> {
        let now = Clock::get()?.unix_timestamp;
        require!(amount > 0, XcmError::InvalidAmount);
        require!(
            timelock > now,
            XcmError::TimelockInPast
        );
        require!(
            receiver != Pubkey::default(),
            XcmError::InvalidAddress
        );
        require!(
            refund_addr != Pubkey::default(),
            XcmError::InvalidAddress
        );

        let escrow_key = ctx.accounts.escrow.key();

        match mint {
            None => {
                // Native SOL: move lamports into the escrow PDA.
                let ix = system_instruction::transfer(
                    &ctx.accounts.funder.key(),
                    &escrow_key,
                    amount,
                );
                invoke(
                    &ix,
                    &[
                        ctx.accounts.funder.to_account_info(),
                        ctx.accounts.escrow.to_account_info(),
                    ],
                )?;
            }
            Some(mint_pk) => {
                require!(
                    ctx.accounts.token_program.key() == anchor_spl::token::ID,
                    XcmError::InvalidTokenProgram
                );
                // Validate the funder's token account (untrusted input).
                let funder_token = TokenAccount::try_deserialize(
                    &mut &ctx.accounts.funder_token.data.borrow()[..],
                )
                .map_err(|_| XcmError::InvalidTokenAccount)?;
                require!(
                    ctx.accounts.funder_token.owner == &anchor_spl::token::ID,
                    XcmError::InvalidTokenAccount
                );
                require!(funder_token.mint == mint_pk, XcmError::MintMismatch);
                require!(
                    funder_token.owner == ctx.accounts.funder.key(),
                    XcmError::InvalidTokenAccountOwner
                );
                require!(funder_token.amount >= amount, XcmError::InsufficientFunds);
                // Validate the pre-created vault: correct mint, owned by the escrow
                // PDA, and empty (fresh vault — prevents double-funding tricks).
                let vault = TokenAccount::try_deserialize(
                    &mut &ctx.accounts.escrow_token.data.borrow()[..],
                )
                .map_err(|_| XcmError::InvalidTokenAccount)?;
                require!(
                    ctx.accounts.escrow_token.owner == &anchor_spl::token::ID,
                    XcmError::InvalidTokenAccount
                );
                require!(vault.mint == mint_pk, XcmError::MintMismatch);
                require!(vault.owner == escrow_key, XcmError::InvalidTokenAccountOwner);
                require!(vault.amount == 0, XcmError::VaultNotEmpty);

                let cpi_ctx = CpiContext::new(
                    ctx.accounts.token_program.to_account_info(),
                    token::Transfer {
                        from: ctx.accounts.funder_token.to_account_info(),
                        to: ctx.accounts.escrow_token.to_account_info(),
                        authority: ctx.accounts.funder.to_account_info(),
                    },
                );
                token::transfer(cpi_ctx, amount)?;
            }
        }

        let escrow = &mut ctx.accounts.escrow;
        escrow.receiver = receiver;
        escrow.refund_addr = refund_addr;
        escrow.hashlock = hashlock;
        escrow.timelock = timelock;
        escrow.mint = mint;
        escrow.amount = amount;
        escrow.fill_id = fill_id;
        escrow.arbiter = arbiter;
        escrow.exclusive_claimer = exclusive_claimer;
        escrow.exclusive_until = exclusive_until;
        escrow.bump = ctx.bumps.escrow;
        Ok(())
    }

    /// Claim branch: reveal the preimage before the timelock.
    ///
    /// Requires `sha256(preimage) == hashlock` (via `solana_program::hash::hash`,
    /// SHA-256 — byte-compatible with the EVM `sha256` precompile) and
    /// `now < timelock`. Pays the full escrowed `amount` to `receiver`.
    /// Anyone may submit the transaction (payout is hardcoded), except during the
    /// exclusive window: while `exclusive_until > now`, only `exclusive_claimer`
    /// may call (§8 — prevents claim races on solver-routed fills).
    pub fn withdraw(ctx: Context<Withdraw>, preimage: [u8; 32]) -> Result<()> {
        let now = Clock::get()?.unix_timestamp;
        // Copy the fields we need: the escrow account is closed at the end of
        // this instruction (`close` constraint), so we must not hold borrows.
        let (receiver, hashlock, timelock, mint, amount, fill_id, exclusive_claimer, exclusive_until, bump) = {
            let e = &ctx.accounts.escrow;
            (
                e.receiver,
                e.hashlock,
                e.timelock,
                e.mint,
                e.amount,
                e.fill_id,
                e.exclusive_claimer,
                e.exclusive_until,
                e.bump,
            )
        };
        require!(
            hash(&preimage).to_bytes() == hashlock,
            XcmError::InvalidPreimage
        );
        require!(now < timelock, XcmError::TimelockExpired);
        if exclusive_until > now {
            require!(
                exclusive_claimer == Some(ctx.accounts.claimer.key()),
                XcmError::NotExclusiveClaimer
            );
        }
        require!(
            ctx.accounts.receiver.key() == receiver,
            XcmError::ReceiverMismatch
        );

        let escrow_key = ctx.accounts.escrow.key();
        let seeds: &[&[u8]] = &[
            HTLC_SEED,
            fill_id.as_ref(),
            hashlock.as_ref(),
            &[bump],
        ];

        match mint {
            None => {
                // SOL: direct lamport mutation (program-owned PDA cannot use
                // system_instruction::transfer). Rent is reclaimed to receiver
                // by the `close = receiver` constraint.
                let escrow_info = ctx.accounts.escrow.to_account_info();
                let receiver_info = ctx.accounts.receiver.to_account_info();
                require!(escrow_info.lamports() >= amount, XcmError::InsufficientFunds);
                **escrow_info.try_borrow_mut_lamports()? -= amount;
                **receiver_info.try_borrow_mut_lamports()? += amount;
            }
            Some(mint_pk) => {
                let v = VaultAccounts {
                    escrow: ctx.accounts.escrow.to_account_info(),
                    escrow_token: ctx.accounts.escrow_token.to_account_info(),
                    dest_token: ctx.accounts.receiver_token.to_account_info(),
                    rent_dest: ctx.accounts.receiver.to_account_info(),
                    token_program: ctx.accounts.token_program.to_account_info(),
                };
                vault_transfer(&v, &escrow_key, mint_pk, &receiver, amount, seeds)?;
                vault_close(&v, seeds)?;
            }
        }
        // Escrow data account closed by the `close = receiver` constraint →
        // rent reclaimed to `receiver`.
        Ok(())
    }

    /// Timelock branch: after expiry, anyone may trigger the refund.
    ///
    /// Requires `now >= timelock`. Pays the full escrowed `amount` to the EXPLICIT
    /// `refund_addr` recorded at lock time — never an implied sender.
    pub fn refund(ctx: Context<Refund>) -> Result<()> {
        let now = Clock::get()?.unix_timestamp;
        let (refund_addr, timelock, mint, amount, fill_id, hashlock, bump) = {
            let e = &ctx.accounts.escrow;
            (
                e.refund_addr,
                e.timelock,
                e.mint,
                e.amount,
                e.fill_id,
                e.hashlock,
                e.bump,
            )
        };
        require!(now >= timelock, XcmError::TimelockNotExpired);
        require!(
            ctx.accounts.refund_addr.key() == refund_addr,
            XcmError::RefundAddrMismatch
        );

        let escrow_key = ctx.accounts.escrow.key();
        let seeds: &[&[u8]] = &[
            HTLC_SEED,
            fill_id.as_ref(),
            hashlock.as_ref(),
            &[bump],
        ];

        match mint {
            None => {
                // SOL: direct lamport mutation. Rent reclaimed to refund_addr
                // by the `close = refund_addr` constraint.
                let escrow_info = ctx.accounts.escrow.to_account_info();
                let refund_info = ctx.accounts.refund_addr.to_account_info();
                require!(escrow_info.lamports() >= amount, XcmError::InsufficientFunds);
                **escrow_info.try_borrow_mut_lamports()? -= amount;
                **refund_info.try_borrow_mut_lamports()? += amount;
            }
            Some(mint_pk) => {
                let v = VaultAccounts {
                    escrow: ctx.accounts.escrow.to_account_info(),
                    escrow_token: ctx.accounts.escrow_token.to_account_info(),
                    dest_token: ctx.accounts.refund_token.to_account_info(),
                    rent_dest: ctx.accounts.refund_addr.to_account_info(),
                    token_program: ctx.accounts.token_program.to_account_info(),
                };
                vault_transfer(&v, &escrow_key, mint_pk, &refund_addr, amount, seeds)?;
                vault_close(&v, seeds)?;
            }
        }
        // Escrow data account closed by the `close = refund_addr` constraint →
        // rent reclaimed to `refund_addr`.
        Ok(())
    }

    /// **MEDIATED** arbitration branch (opt-in at lock time only).
    ///
    /// # Trust note
    ///
    /// Naming an `arbiter` converts the swap from trustless to **mediated**: the
    /// arbiter can UNILATERALLY redirect the escrowed funds before timelock expiry
    /// on its ed25519 signature alone — no counterparty signature is required.
    /// Per SPEC.md §5, the venue UI MUST badge arbiter-enabled offers as mediated.
    /// `arbiter: None` (default) disables this branch entirely (pure HTLC).
    ///
    /// # Authorization
    ///
    /// The transaction MUST include a native Ed25519Program signature-verification
    /// instruction immediately before this instruction. The handler locates it via
    /// the instructions sysvar and requires:
    /// * its program id is the Ed25519Program,
    /// * it carries exactly one signature whose public key is the escrow's
    ///   `arbiter`,
    /// * the signed message is exactly
    ///   `"XCM-ARBITRATE-v1" || escrow_pda (32) || recipients (32 each) || amounts (u64 LE each)`,
    ///   with all signature/pubkey/message bytes inline in that instruction.
    ///
    /// The Solana runtime cryptographically verifies the ed25519 signature when it
    /// executes the precompile instruction, so the program performs no curve math
    /// itself (direct in-program ed25519 verification exceeds the SBF stack
    /// limit). A forged or mismatched precompile instruction fails closed with
    /// `InvalidArbiterSignature`.
    ///
    /// The verified split then executes immediately. `sum(amounts)` must equal
    /// exactly the escrowed `amount`. Reclaimed rent goes to `refund_addr`
    /// (documented default).
    pub fn arbitrate<'info>(
        ctx: Context<'_, '_, '_, 'info, Arbitrate<'info>>,
        recipients: Vec<Pubkey>,
        amounts: Vec<u64>,
    ) -> Result<()> {
        let arbiter = ctx
            .accounts
            .escrow
            .arbiter
            .ok_or(XcmError::ArbiterNotSet)?;
        require!(
            !recipients.is_empty() && recipients.len() == amounts.len(),
            XcmError::PayoutLengthMismatch
        );
        let total = amounts
            .iter()
            .try_fold(0u64, |acc, a| acc.checked_add(*a))
            .ok_or(XcmError::PayoutLengthMismatch)?;
        let (refund_addr, mint, amount, fill_id, hashlock, bump) = {
            let e = &ctx.accounts.escrow;
            (
                e.refund_addr,
                e.mint,
                e.amount,
                e.fill_id,
                e.hashlock,
                e.bump,
            )
        };
        // The arbiter's split must account for exactly the escrowed funds.
        require!(total == amount, XcmError::PayoutTotalMismatch);
        // The rent destination must be the escrow's explicit refund address.
        require!(
            ctx.accounts.refund_addr.key() == refund_addr,
            XcmError::RefundAddrMismatch
        );

        // Rebuild the signed message and authorize it via the Ed25519Program
        // precompile instruction that must immediately precede this one.
        // The runtime verifies the cryptographic signature when executing the
        // precompile; here we only bind (program id, pubkey, message) so the
        // program itself performs no curve math.
        let escrow_key = ctx.accounts.escrow.key();
        let mut msg = Vec::with_capacity(
            ARBITRATE_DOMAIN.len() + 32 + recipients.len() * 32 + amounts.len() * 8,
        );
        msg.extend_from_slice(ARBITRATE_DOMAIN);
        msg.extend_from_slice(escrow_key.as_ref());
        for r in &recipients {
            msg.extend_from_slice(r.as_ref());
        }
        for a in &amounts {
            msg.extend_from_slice(&a.to_le_bytes());
        }
        verify_ed25519_precompile(
            &ctx.accounts.instructions_sysvar.to_account_info(),
            &arbiter,
            &msg,
        )?;

        let seeds: &[&[u8]] = &[
            HTLC_SEED,
            fill_id.as_ref(),
            hashlock.as_ref(),
            &[bump],
        ];
        let signer_seeds = &[seeds];

        match mint {
            None => {
                // SOL: direct lamport mutation (the escrow PDA is program-owned,
                // so system_instruction::transfer cannot be used). The Anchor
                // `close` constraint reclaims remaining rent to refund_addr.
                require!(
                    ctx.remaining_accounts.len() >= recipients.len(),
                    XcmError::MissingRecipientAccounts
                );
                // Verify sum(amounts) == escrow.amount (checked earlier); ensure
                // the escrow holds at least `amount` beyond rent.
                let escrow_info = ctx.accounts.escrow.to_account_info();
                for (i, (recipient, payout)) in
                    recipients.iter().zip(amounts.iter()).enumerate()
                {
                    let dest = &ctx.remaining_accounts[i];
                    require!(
                        dest.key() == *recipient,
                        XcmError::RecipientAccountMismatch
                    );
                    require!(dest.is_writable, XcmError::RecipientAccountMismatch);
                    // Direct lamport transfer: subtract from escrow, add to dest.
                    // The escrow PDA is owned by this program, so we can mutate
                    // its lamports directly (no system CPI needed).
                    let escrow_start = escrow_info.lamports();
                    require!(
                        escrow_start >= *payout,
                        XcmError::InsufficientFunds
                    );
                    **escrow_info.try_borrow_mut_lamports()? -= *payout;
                    **dest.try_borrow_mut_lamports()? += *payout;
                }
            }
            Some(mint_pk) => {
                require!(
                    ctx.accounts.token_program.key() == anchor_spl::token::ID,
                    XcmError::InvalidTokenProgram
                );
                require!(
                    ctx.remaining_accounts.len() >= recipients.len(),
                    XcmError::MissingRecipientAccounts
                );
                // Validate the vault once.
                let vault = TokenAccount::try_deserialize(
                    &mut &ctx.accounts.escrow_token.data.borrow()[..],
                )
                .map_err(|_| XcmError::InvalidTokenAccount)?;
                require!(
                    ctx.accounts.escrow_token.owner == &anchor_spl::token::ID,
                    XcmError::InvalidTokenAccount
                );
                require!(vault.mint == mint_pk, XcmError::MintMismatch);
                require!(
                    vault.owner == escrow_key,
                    XcmError::InvalidTokenAccountOwner
                );
                for (i, (recipient, payout)) in
                    recipients.iter().zip(amounts.iter()).enumerate()
                {
                    let dest = &ctx.remaining_accounts[i];
                    let dest_token = TokenAccount::try_deserialize(
                        &mut &dest.data.borrow()[..],
                    )
                    .map_err(|_| XcmError::InvalidTokenAccount)?;
                    require!(
                        dest.owner == &anchor_spl::token::ID,
                        XcmError::InvalidTokenAccount
                    );
                    require!(dest_token.mint == mint_pk, XcmError::MintMismatch);
                    require!(
                        dest_token.owner == *recipient,
                        XcmError::RecipientAccountMismatch
                    );
                    require!(dest.is_writable, XcmError::RecipientAccountMismatch);
                    let cpi_ctx = CpiContext::new_with_signer(
                        ctx.accounts.token_program.to_account_info(),
                        token::Transfer {
                            from: ctx.accounts.escrow_token.clone(),
                            to: dest.clone(),
                            authority: ctx.accounts.escrow.to_account_info(),
                        },
                        signer_seeds,
                    );
                    token::transfer(cpi_ctx, *payout)?;
                }
                // Close the emptied vault; rent → refund_addr (documented default).
                let close_cpi = CpiContext::new_with_signer(
                    ctx.accounts.token_program.to_account_info(),
                    token::CloseAccount {
                        account: ctx.accounts.escrow_token.clone(),
                        destination: ctx.accounts.refund_addr.to_account_info(),
                        authority: ctx.accounts.escrow.to_account_info(),
                    },
                    signer_seeds,
                );
                token::close_account(close_cpi)?;
            }
        }
        // Escrow data account closed by the `close = refund_addr` constraint.
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

/// On-chain HTLC escrow. Role-explicit per SPEC.md §5: the program knows
/// `receiver` / `refund_addr` / keys — never "maker"/"taker" labels.
#[account]
pub struct HtlcEscrow {
    /// Claim branch pays here.
    pub receiver: Pubkey,
    /// Timelock branch pays here. EXPLICIT — refund never assumes a sender.
    pub refund_addr: Pubkey,
    /// sha256(secret); secret generated by the maker per fill.
    pub hashlock: [u8; 32],
    /// Unix timestamp; claim requires now < timelock, refund requires now >= timelock.
    pub timelock: i64,
    /// None = native SOL escrow; Some = SPL mint.
    pub mint: Option<Pubkey>,
    /// Escrowed amount (lamports / token base units).
    pub amount: u64,
    /// sha256(offerId || fillNonce); unique per fill, bound into the PDA seeds.
    pub fill_id: [u8; 32],
    /// Opt-in MEDIATED arbitration key. None = pure HTLC.
    pub arbiter: Option<Pubkey>,
    /// Auction-winner exclusive claim window (§8).
    pub exclusive_claimer: Option<Pubkey>,
    pub exclusive_until: i64,
    /// PDA bump for ["htlc", fill_id, hashlock].
    pub bump: u8,
}

impl HtlcEscrow {
    /// 8 (discriminator) + 32 + 32 + 32 + 8 + (1+32) + 8 + 32 + (1+32) + (1+32) + 8 + 1
    pub const SPACE: usize = 260;
}

// ---------------------------------------------------------------------------
// Contexts
// ---------------------------------------------------------------------------

#[derive(Accounts)]
#[instruction(
    receiver: Pubkey, refund_addr: Pubkey, hashlock: [u8; 32], timelock: i64,
    mint: Option<Pubkey>, amount: u64, fill_id: [u8; 32],
    arbiter: Option<Pubkey>, exclusive_claimer: Option<Pubkey>, exclusive_until: i64
)]
pub struct Initialize<'info> {
    #[account(mut)]
    pub funder: Signer<'info>,
    #[account(
        init,
        payer = funder,
        space = HtlcEscrow::SPACE,
        seeds = [HTLC_SEED, fill_id.as_ref(), hashlock.as_ref()],
        bump,
    )]
    pub escrow: Account<'info, HtlcEscrow>,
    /// CHECK: claim destination. Unvalidated address — a wrong value only harms
    /// the locker who chose it; funds can only ever go here on the claim branch.
    pub receiver: UncheckedAccount<'info>,
    /// CHECK: explicit refund destination. Unvalidated for the same reason.
    pub refund_addr: UncheckedAccount<'info>,
    /// CHECK: SPL only — funder's token account. Validated in the handler when
    /// `mint.is_some()`. Pass any account (e.g. the escrow itself) for SOL fills.
    pub funder_token: UncheckedAccount<'info>,
    /// CHECK: SPL only — pre-created escrow vault token account whose authority
    /// must be the escrow PDA. Validated in the handler when `mint.is_some()`.
    /// Pass any account for SOL fills.
    pub escrow_token: UncheckedAccount<'info>,
    pub system_program: Program<'info, System>,
    /// CHECK: SPL only — must be the SPL Token program. Validated in the handler
    /// when `mint.is_some()`. Pass any account for SOL fills.
    pub token_program: UncheckedAccount<'info>,
}

#[derive(Accounts)]
pub struct Withdraw<'info> {
    /// Anyone may submit (payout is hardcoded to `receiver`); exclusivity is
    /// enforced in the handler.
    pub claimer: Signer<'info>,
    #[account(
        mut,
        seeds = [HTLC_SEED, escrow.fill_id.as_ref(), escrow.hashlock.as_ref()],
        bump = escrow.bump,
        close = receiver,
    )]
    pub escrow: Account<'info, HtlcEscrow>,
    /// CHECK: must equal `escrow.receiver` (checked in handler); receives the
    /// funds and the reclaimed rent.
    #[account(mut)]
    pub receiver: UncheckedAccount<'info>,
    /// CHECK: SPL only — escrow vault token account. Validated in the handler.
    #[account(mut)]
    pub escrow_token: UncheckedAccount<'info>,
    /// CHECK: SPL only — receiver's token account for `mint`. Validated in the handler.
    #[account(mut)]
    pub receiver_token: UncheckedAccount<'info>,
    pub system_program: Program<'info, System>,
    /// CHECK: SPL only. Validated in the handler when `escrow.mint.is_some()`.
    pub token_program: UncheckedAccount<'info>,
}

#[derive(Accounts)]
pub struct Refund<'info> {
    /// Anyone may call once the timelock expires.
    pub caller: Signer<'info>,
    #[account(
        mut,
        seeds = [HTLC_SEED, escrow.fill_id.as_ref(), escrow.hashlock.as_ref()],
        bump = escrow.bump,
        close = refund_addr,
    )]
    pub escrow: Account<'info, HtlcEscrow>,
    /// CHECK: must equal `escrow.refund_addr` (checked in handler); receives the
    /// funds and the reclaimed rent.
    #[account(mut)]
    pub refund_addr: UncheckedAccount<'info>,
    /// CHECK: SPL only — escrow vault token account. Validated in the handler.
    #[account(mut)]
    pub escrow_token: UncheckedAccount<'info>,
    /// CHECK: SPL only — refund address's token account for `mint`. Validated in handler.
    #[account(mut)]
    pub refund_token: UncheckedAccount<'info>,
    pub system_program: Program<'info, System>,
    /// CHECK: SPL only. Validated in the handler when `escrow.mint.is_some()`.
    pub token_program: UncheckedAccount<'info>,
}

#[derive(Accounts)]
pub struct Arbitrate<'info> {
    /// Anyone may submit; authorization comes from the arbiter's ed25519
    /// precompile instruction, verified in the handler via the instructions
    /// sysvar.
    pub caller: Signer<'info>,
    #[account(
        mut,
        seeds = [HTLC_SEED, escrow.fill_id.as_ref(), escrow.hashlock.as_ref()],
        bump = escrow.bump,
        close = refund_addr,
    )]
    pub escrow: Account<'info, HtlcEscrow>,
    /// CHECK: reclaimed rent destination (documented default). Must equal
    /// `escrow.refund_addr` — checked in the handler.
    #[account(mut)]
    pub refund_addr: UncheckedAccount<'info>,
    /// CHECK: SPL only — escrow vault token account. Validated in the handler.
    #[account(mut)]
    pub escrow_token: AccountInfo<'info>,
    pub system_program: Program<'info, System>,
    /// CHECK: SPL only. Validated in the handler when `escrow.mint.is_some()`.
    pub token_program: UncheckedAccount<'info>,
    /// CHECK: the instructions sysvar (address-constrained). Used to locate the
    /// Ed25519Program signature-verification instruction that must immediately
    /// precede this instruction; the precompile's data is parsed but never
    /// trusted for the cryptographic check (the runtime verifies the signature).
    #[account(address = IX_SYSVAR_ID)]
    pub instructions_sysvar: UncheckedAccount<'info>,
    // remaining_accounts: one destination account per recipient, in order —
    //   SOL: writable system accounts owned by each recipient pubkey.
    //   SPL: writable token accounts (mint == escrow.mint) owned by each recipient.
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Authorize an arbiter action via the native Ed25519Program precompile.
///
/// Requires the instruction immediately preceding the current one to be an
/// Ed25519Program signature-verification instruction carrying exactly one
/// signature, signed by `expected_pubkey`, over exactly `expected_msg`, with
/// all signature/pubkey/message bytes inline in that instruction's data
/// (each `*_instruction_index == u16::MAX`).
///
/// Security argument: the Solana runtime cryptographically verifies the ed25519
/// signature when it executes the precompile instruction — a transaction
/// containing a forged precompile instruction never reaches this program.
/// What the program must still bind (and does here) is *which* pubkey and
/// *which* message were verified: an attacker can always append a *validly
/// signed* precompile instruction of their own (e.g. self-signed over a
/// different message), so this check rejects anything not signed by the
/// escrow's arbiter over the exact expected message. The program performs no
/// curve math itself, avoiding the SBF stack-limit violations of in-program
/// ed25519 verification.
fn verify_ed25519_precompile(
    ix_sysvar: &AccountInfo,
    expected_pubkey: &Pubkey,
    expected_msg: &[u8],
) -> Result<()> {
    let current_idx =
        load_current_index_checked(ix_sysvar).map_err(|_| XcmError::InvalidArbiterSignature)?
            as usize;
    // The precompile instruction must immediately precede this one.
    let pre_idx = current_idx
        .checked_sub(1)
        .ok_or(XcmError::InvalidArbiterSignature)?;
    let pre_ix = load_instruction_at_checked(pre_idx, ix_sysvar)
        .map_err(|_| XcmError::InvalidArbiterSignature)?;
    require_keys_eq!(
        pre_ix.program_id,
        ed25519_program::ID,
        XcmError::InvalidArbiterSignature
    );

    // Ed25519Program instruction layout: u8 num_signatures, u8 padding, then
    // per signature: u16 signature_offset, u16 signature_instruction_index,
    // u16 public_key_offset, u16 public_key_instruction_index,
    // u16 message_data_offset, u16 message_data_size,
    // u16 message_instruction_index.
    let data = &pre_ix.data;
    require!(data.len() >= 2 + 14, XcmError::InvalidArbiterSignature);
    require!(data[0] == 1, XcmError::InvalidArbiterSignature);
    let u16_at = |off: usize| -> Result<usize> {
        data.get(off..off + 2)
            .and_then(|b| b.try_into().ok())
            .map(|b: [u8; 2]| u16::from_le_bytes(b) as usize)
            .ok_or(error!(XcmError::InvalidArbiterSignature))
    };
    let sig_off = u16_at(2)?;
    let pk_off = u16_at(6)?;
    let msg_off = u16_at(10)?;
    let msg_size = u16_at(12)?;
    // All signature/pubkey/message bytes must be inline in the precompile
    // instruction itself (u16::MAX = "current instruction"), never borrowed
    // from another instruction's data.
    for off in [4usize, 8, 14] {
        require!(u16_at(off)? == u16::MAX as usize, XcmError::InvalidArbiterSignature);
    }
    let sig_end = sig_off.checked_add(64).ok_or(XcmError::InvalidArbiterSignature)?;
    let pk_end = pk_off.checked_add(32).ok_or(XcmError::InvalidArbiterSignature)?;
    let msg_end = msg_off.checked_add(msg_size).ok_or(XcmError::InvalidArbiterSignature)?;
    require!(data.len() >= sig_end, XcmError::InvalidArbiterSignature);
    require!(data.len() >= pk_end, XcmError::InvalidArbiterSignature);
    require!(data.len() >= msg_end, XcmError::InvalidArbiterSignature);

    require!(
        data[pk_off..pk_end] == expected_pubkey.to_bytes(),
        XcmError::InvalidArbiterSignature
    );
    require!(
        &data[msg_off..msg_end] == expected_msg,
        XcmError::InvalidArbiterSignature
    );
    // The 64 signature bytes were already verified by the runtime when it
    // executed the precompile instruction; pubkey + message binding above is
    // sufficient.
    Ok(())
}

/// The accounts involved in SPL vault operations, collected so one helper pair
/// serves `withdraw`, `refund`, and `arbitrate`.
struct VaultAccounts<'info> {
    escrow: AccountInfo<'info>,
    escrow_token: AccountInfo<'info>,
    dest_token: AccountInfo<'info>,
    rent_dest: AccountInfo<'info>,
    token_program: AccountInfo<'info>,
}

/// Transfer `amount` of SPL tokens from the escrow vault to `dest_token`,
/// validating the vault (mint, PDA authority, balance) and the destination
/// (mint, expected owner). Signed by the escrow PDA.
fn vault_transfer(
    v: &VaultAccounts,
    escrow_key: &Pubkey,
    mint_pk: Pubkey,
    expected_dest_owner: &Pubkey,
    amount: u64,
    seeds: &[&[u8]],
) -> Result<()> {
    require!(
        v.token_program.key() == anchor_spl::token::ID,
        XcmError::InvalidTokenProgram
    );
    let vault =
        TokenAccount::try_deserialize(&mut &v.escrow_token.data.borrow()[..])
            .map_err(|_| XcmError::InvalidTokenAccount)?;
    require!(
        v.escrow_token.owner == &anchor_spl::token::ID,
        XcmError::InvalidTokenAccount
    );
    require!(vault.mint == mint_pk, XcmError::MintMismatch);
    require!(
        vault.owner == *escrow_key,
        XcmError::InvalidTokenAccountOwner
    );
    require!(vault.amount >= amount, XcmError::InsufficientFunds);

    let dest =
        TokenAccount::try_deserialize(&mut &v.dest_token.data.borrow()[..])
            .map_err(|_| XcmError::InvalidTokenAccount)?;
    require!(
        v.dest_token.owner == &anchor_spl::token::ID,
        XcmError::InvalidTokenAccount
    );
    require!(dest.mint == mint_pk, XcmError::MintMismatch);
    require!(
        dest.owner == *expected_dest_owner,
        XcmError::RecipientAccountMismatch
    );
    require!(v.dest_token.is_writable, XcmError::RecipientAccountMismatch);

    let signer_seeds = &[seeds];
    let cpi_ctx = CpiContext::new_with_signer(
        v.token_program.clone(),
        token::Transfer {
            from: v.escrow_token.clone(),
            to: v.dest_token.clone(),
            authority: v.escrow.clone(),
        },
        signer_seeds,
    );
    token::transfer(cpi_ctx, amount)
}

/// Close the SPL vault token account via the SPL `CloseAccount` instruction
/// (authority = escrow PDA), sending reclaimed rent to `rent_dest`.
fn vault_close(v: &VaultAccounts, seeds: &[&[u8]]) -> Result<()> {
    let signer_seeds = &[seeds];
    let cpi_ctx = CpiContext::new_with_signer(
        v.token_program.clone(),
        token::CloseAccount {
            account: v.escrow_token.clone(),
            destination: v.rent_dest.clone(),
            authority: v.escrow.clone(),
        },
        signer_seeds,
    );
    token::close_account(cpi_ctx)
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[error_code]
pub enum XcmError {
    #[msg("Escrow amount must be greater than zero")]
    InvalidAmount,
    #[msg("Timelock must be in the future at initialization")]
    TimelockInPast,
    #[msg("Receiver/refund address must not be the default pubkey")]
    InvalidAddress,
    #[msg("Preimage does not match the hashlock")]
    InvalidPreimage,
    #[msg("Timelock has expired; the claim window is closed")]
    TimelockExpired,
    #[msg("Timelock has not expired yet")]
    TimelockNotExpired,
    #[msg("Only the exclusive claimer may withdraw during the exclusive window")]
    NotExclusiveClaimer,
    #[msg("Receiver account does not match the escrow's receiver")]
    ReceiverMismatch,
    #[msg("Refund account does not match the escrow's refund_addr")]
    RefundAddrMismatch,
    #[msg("No arbiter was set at lock time; the arbitrate branch is disabled")]
    ArbiterNotSet,
    #[msg("Arbiter signature verification failed")]
    InvalidArbiterSignature,
    #[msg("Recipients and amounts must be non-empty and the same length")]
    PayoutLengthMismatch,
    #[msg("Payout amounts must sum to exactly the escrowed amount")]
    PayoutTotalMismatch,
    #[msg("Not enough recipient accounts were provided")]
    MissingRecipientAccounts,
    #[msg("Recipient account does not match the declared recipient")]
    RecipientAccountMismatch,
    #[msg("Expected the SPL Token program")]
    InvalidTokenProgram,
    #[msg("Not a valid SPL token account")]
    InvalidTokenAccount,
    #[msg("Token account mint does not match the escrow mint")]
    MintMismatch,
    #[msg("Token account owner is not the expected authority")]
    InvalidTokenAccountOwner,
    #[msg("Insufficient funds in the token account")]
    InsufficientFunds,
    #[msg("Escrow vault token account must be empty at initialization")]
    VaultNotEmpty,
}
