// Vercel build step: bakes the NIGHTSPIRE_RELAY_URL env var into config.js,
// so visitors land on a board already pointed at the relay — no pasting needed.
//
// Set as the Vercel Build Command (with Root Directory = venue-web):
//   node build.mjs
// and add the env var NIGHTSPIRE_RELAY_URL = https://<your-railway-url>.
//
// If the env var is unset, config.js leaves the default alone (localhost),
// which keeps local dev (`npx serve .`) working unchanged.
import { writeFileSync } from 'node:fs';

const url = (process.env.NIGHTSPIRE_RELAY_URL || '').trim().replace(/\/+$/, '');
const body = url
  ? `window.NIGHTSPIRE_RELAY_URL = ${JSON.stringify(url)};\n`
  : `window.NIGHTSPIRE_RELAY_URL = null;\n`;
writeFileSync(
  new URL('./config.js', import.meta.url),
  `/* generated by build.mjs — do not edit by hand */\n${body}`,
);
console.log(
  url
    ? `config.js: relay default -> ${url}`
    : 'config.js: NIGHTSPIRE_RELAY_URL not set — keeping localhost default',
);
